### ISSUE TITLE
Wrong cloudformation template for Asia Pacific (Singapore) Region

### ISSUE THREAD

**Issue by shamal** [awsdocs/aws-codedeploy-user-guide#13]
The indicated cloudformation template s3 url for Asia Pacific (Singapore) Region throws error
`Template validation error: Template error: Unable to get mapping for RegionOS2AMI::ap-southeast-1::Linux`

[](http://s3-ap-southeast-1.amazonaws.com/aws-codedeploy-ap-southeast-1/templates/latest/CodeDeploy_SampleCF_Template.json)

**Comment by markiver** [comment]
Hello,

Thank you for reporting this. I apologize for any frustration this caused you.

I cannot reproduce what you are experiencing. The following URL successfully downloads the template:

http://s3-ap-southeast-1.amazonaws.com/aws-codedeploy-ap-southeast-1/templates/latest/CodeDeploy_SampleCF_Template.json

If you continue to experience this, please let us know, and be sure to include the exact URL that is not working.

Kind regards,

Mark
