### ISSUE TITLE
script stop_server has spaces in variable declaration

### ISSUE THREAD

**Issue by 1robroos** [awsdocs/aws-codedeploy-user-guide#41]
The script `stop_server` has two spaces around the = statement, and that generates an error at deployment time.
Script now looks like
```
#!/bin/bash
isExistApp = `pgrep httpd`
if [[ -n  $isExistApp ]]; then
    service httpd stop        
fi
```
Error is:
```
/opt/codedeploy-agent/deployment-root/88fa5063-f0af-43ce-bd0e-fe2e5dba8e42/d-FQROXFX96/deployment-archive/scripts/stop_server: line 2: isExistApp: command not found
```

Script should look like:
```
#!/bin/bash
isExistApp=`pgrep httpd`
if [[ -n  $isExistApp ]]; then
    service httpd stop        
fi
```
( Spaces removed in the var declaration )

**Comment by zjayers** [comment]
As of 1/20/23, this is still an issue. 

![Screenshot 2023-01-20 at 1 13 17 PM](https://user-images.githubusercontent.com/61464942/213797159-e6b928b9-800d-4ba9-b137-ddacfd31657e.png)

**Comment by amznchrs** [comment]
@zjayers - The docs that mention this script have been updated. Thank you!
The updated page is here: https://docs.aws.amazon.com/codedeploy/latest/userguide/tutorials-wordpress-configure-content.html
