### ISSUE TITLE
No--targets option for aws ssm describe-association

### ISSUE THREAD

**Issue by sudhakarau1** [awsdocs/aws-codedeploy-user-guide#46]
https://github.com/awsdocs/aws-codedeploy-user-guide/blob/main/doc_source/tutorials-wordpress-clean-up.md Step 4 has:
```
aws ssm describe-association --name AWS-ConfigureAWSPackage --targets Key=tag:Name,Values=CodeDeployDemo
```
which results in an error:
```
Unknown options: --targets, Key=tag:Name,Values=CodeDeployDemo
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
