### ISSUE TITLE
I couldn't find the link to the site. If you know of one, could you please let me know?

### ISSUE THREAD

**Issue by kajirikajiri** [awsdocs/aws-codedeploy-user-guide#48]
Target html.
https://docs.aws.amazon.com/codedeploy/latest/userguide/tutorial-ecs-prereqs.html

Target markdown.
https://github.com/awsdocs/aws-codedeploy-user-guide/blob/main/doc_source/tutorial-ecs-prereqs.md

I noticed that the link to the red-lined part of the image did not exist, so I tried to find the linked file, but could not find it.
Does anyone know where the link to this file is?

<img width="1178" alt="スクリーンショット 2021-08-09 0 18 09" src="https://user-images.githubusercontent.com/37785038/128637005-31d1e301-cca8-4db0-a3b6-cfe33fcc0f3b.png">

Required links page.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-blue-green.html

Maybe need markdown.
https://github.com/awsdocs/aws-codedeploy-user-guide/blob/main/doc_source/create-blue-green.md

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
