### ISSUE TITLE
Typo in deployment-configurations.md

### ISSUE THREAD

**Issue by hassankhan** [awsdocs/aws-codedeploy-user-guide#9]
In the table under [**Predefined Deployment Configurations for an AWS Lambda Compute Platform**](https://github.com/awsdocs/aws-codedeploy-user-guide/blob/master/doc_source/deployment-configurations.md#predefined-deployment-configurations-for-an-aws-lambda-compute-platform), the description for `CodeDeployDefault.LambdaLinear10PercentEvery10Minutes` states the following:

> Shifts 10 percent of traffic every 30 minutes until all traffic is shifted.

Shouldn't this be every 10 minutes instead?

**Comment by markiver** [comment]
Hello,

Thank you for your feedback. You are correct, and this is now updated in the HTML User Guide and the open source User Guide here on GitHub.

Input from customers like you is valuable and helps us keep our documentation as current and useful as possible. 

Thank you again.

Mark
